name: astro_hub
description: A craft reservation system for inter galactic travellers

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.1
  firebase_auth: ^4.7.3
  provider: ^6.0.5
  flutter_spinkit: ^5.2.0
  glassmorphism: ^3.0.0
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/icons/

  fonts:
    - family: SairaSemiCondensed
      fonts:
        - asset: assets/fonts/SairaSemiCondensed-Thin.ttf
          weight: 100
        - asset: assets/fonts/SairaSemiCondensed-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/SairaSemiCondensed-Light.ttf
          weight: 300
        - asset: assets/fonts/SairaSemiCondensed-Regular.ttf
          weight: 400
        - asset: assets/fonts/SairaSemiCondensed-Medium.ttf
          weight: 500
        - asset: assets/fonts/SairaSemiCondensed-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/SairaSemiCondensed-Bold.ttf
          weight: 700
        - asset: assets/fonts/SairaSemiCondensed-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/SairaSemiCondensed-Black.ttf
          weight: 900
        
          style: normal

