// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAD78zhPiCKtJ0a6xZHnlnZTA6h8jgQm9o',
    appId: '1:227612603597:web:1b3c82d9f6c49d55802584',
    messagingSenderId: '227612603597',
    projectId: 'astrohub-3b138',
    authDomain: 'astrohub-3b138.firebaseapp.com',
    storageBucket: 'astrohub-3b138.appspot.com',
    measurementId: 'G-D69PJ5NKGC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpLmAVNW7j02wMY7vDOPDQ45diAVvqCCw',
    appId: '1:227612603597:android:247e07f4e51d38df802584',
    messagingSenderId: '227612603597',
    projectId: 'astrohub-3b138',
    storageBucket: 'astrohub-3b138.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBWAKPyCBtkI9_wh-wjbOZ-G1abWRYcHs',
    appId: '1:227612603597:ios:b85826734c11eed5802584',
    messagingSenderId: '227612603597',
    projectId: 'astrohub-3b138',
    storageBucket: 'astrohub-3b138.appspot.com',
    iosClientId: '227612603597-p7cc9r9v9h0ehuf1pi5oig5jdvhao0h1.apps.googleusercontent.com',
    iosBundleId: 'com.example.astroHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBWAKPyCBtkI9_wh-wjbOZ-G1abWRYcHs',
    appId: '1:227612603597:ios:0f9b57eedb31b174802584',
    messagingSenderId: '227612603597',
    projectId: 'astrohub-3b138',
    storageBucket: 'astrohub-3b138.appspot.com',
    iosClientId: '227612603597-oqn6o2hr5t2cjtoud6snucljqv52gpke.apps.googleusercontent.com',
    iosBundleId: 'com.example.astroHub.RunnerTests',
  );
}
